// Dummy data for the reference pages and the static screens.
//
// It is deliberately *real-shaped* rather than lorem ipsum. Product names,
// codes, units of measure, HSN codes, GST slabs, MOQs and the order lifecycle
// are taken from the Overview doc (§2 product list, §16 lifecycle, §19 payment
// states) so that a component is exercised by the data it will actually meet:
// a 42-character product name, a five-digit stock figure, an eight-state status
// column. Lorem ipsum hides exactly the layout bugs that real data finds.
//
// Money is integer paise. See format.js.
// Nothing here talks to the API. When the backend catches up, these shapes are
// the contract to match.

/* -------------------------------------------------------------------------- */
/* Categories — the §12 taxonomy                                              */
/* -------------------------------------------------------------------------- */

export const categories = [
  {
    slug: 'iv-infusion',
    name: 'I.V. Infusion',
    icon: 'infusion',
    count: 34,
    children: [
      { slug: 'standard-infusion-sets', name: 'Standard Infusion Sets', count: 12 },
      { slug: 'micro-sets', name: 'Micro Sets', count: 8 },
      { slug: 'filter-sets', name: 'Filter Sets', count: 6 },
      { slug: 'specialty-sets', name: 'Specialty Sets', count: 8 },
    ],
  },
  {
    slug: 'extension-lines',
    name: 'Extension Lines',
    icon: 'vitals',
    count: 18,
    children: [
      { slug: 'low-pressure', name: 'Low Pressure', count: 9 },
      { slug: 'high-pressure', name: 'High Pressure', count: 9 },
    ],
  },
  {
    slug: 'connectors',
    name: 'Connectors',
    icon: 'lab',
    count: 15,
    children: [
      { slug: 'needle-free-connectors', name: 'Needle-Free Connectors', count: 10 },
      { slug: 'other-connectors', name: 'Other Connectors', count: 5 },
    ],
  },
  { slug: 'stop-cocks', name: 'Stop Cocks', icon: 'clinical', count: 11, children: [] },
  { slug: 'vial-access', name: 'Vial Access', icon: 'pharma', count: 9, children: [] },
  { slug: 'other-products', name: 'Other Products', icon: 'wound', count: 22, children: [] },
];

/* -------------------------------------------------------------------------- */
/* Products                                                                   */
/* -------------------------------------------------------------------------- */

// `image: null` everywhere, on purpose. §22 asks for actual Ayursurgi product
// photography and explicitly rules out generic stock imagery, so rather than
// dress the system in pictures of somebody else's syringes, ProductImage renders
// a category-glyph placeholder. It is honest about being unfinished, it holds the
// exact aspect ratio the real photo will occupy, and it doubles as the
// missing-image state the catalogue needs anyway.

export const products = [
  {
    id: 'p-polyfusion-airvent',
    code: 'AST-IV-1001',
    name: 'Polyfusion I.V. Infusion Set with Airvent Spike',
    category: 'I.V. Infusion',
    categorySlug: 'iv-infusion',
    subCategory: 'Standard Infusion Sets',
    icon: 'infusion',
    summary: 'Vented spike infusion set with roller clamp and 20 drops/mL chamber, for gravity administration.',
    price: 4250,
    mrp: 5500,
    gst: 12,
    hsn: '90183930',
    uom: 'Piece',
    packSize: '100 pcs / box',
    moq: 100,
    stock: 12400,
    lowStockAt: 2000,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'CE Certificate', 'Product Brochure'],
    specs: [
      ['Tube length', '150 cm'],
      ['Drop factor', '20 drops / mL'],
      ['Spike', 'Vented, ISO 8536-4'],
      ['Filter', '15 µm fluid filter'],
      ['Clamp', 'Roller clamp'],
      ['Sterilisation', 'Ethylene oxide'],
      ['Shelf life', '36 months'],
    ],
    applications: ['Gravity infusion', 'General ward', 'Day-care procedures'],
    image: null,
  },
  {
    id: 'p-polyfusion-micro',
    code: 'AST-IV-1042',
    name: 'Polyfusion Micro Drip Set 60 drops/mL',
    category: 'I.V. Infusion',
    categorySlug: 'iv-infusion',
    subCategory: 'Micro Sets',
    icon: 'infusion',
    summary: 'Paediatric micro drip set with 60 drops/mL burette chamber for precise low-volume delivery.',
    price: 6800,
    mrp: 8200,
    gst: 12,
    hsn: '90183930',
    uom: 'Piece',
    packSize: '50 pcs / box',
    moq: 50,
    stock: 1840,
    lowStockAt: 2000,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'CE Certificate'],
    specs: [
      ['Tube length', '150 cm'],
      ['Drop factor', '60 drops / mL'],
      ['Chamber', 'Micro drip, transparent'],
      ['Filter', '15 µm fluid filter'],
      ['Sterilisation', 'Ethylene oxide'],
    ],
    applications: ['Paediatric infusion', 'Neonatal care', 'Controlled dosing'],
    image: null,
  },
  {
    id: 'p-polyvol-burette',
    code: 'AST-BU-2210',
    name: 'Polyvol Burette Set 150 mL with Graduated Chamber',
    category: 'I.V. Infusion',
    categorySlug: 'iv-infusion',
    subCategory: 'Specialty Sets',
    icon: 'infusion',
    summary: 'Graduated 150 mL burette chamber with air vent and injection site for volumetric control.',
    price: 18500,
    mrp: 22000,
    gst: 12,
    hsn: '90183930',
    uom: 'Piece',
    packSize: '25 pcs / box',
    moq: 25,
    stock: 420,
    lowStockAt: 500,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'CE Certificate', 'Compliance Declaration'],
    specs: [
      ['Chamber volume', '150 mL'],
      ['Graduation', '1 mL increments'],
      ['Drop factor', '60 drops / mL'],
      ['Injection site', 'Latex-free Y-site'],
      ['Air vent', 'Hydrophobic, 0.2 µm'],
    ],
    applications: ['Volumetric infusion', 'ICU', 'Paediatric ward'],
    image: null,
  },
  {
    id: 'p-extension-high',
    code: 'AST-EX-3305',
    name: 'High Pressure Extension Line 200 cm, 1200 psi',
    category: 'Extension Lines',
    categorySlug: 'extension-lines',
    subCategory: 'High Pressure',
    icon: 'vitals',
    summary: 'Kink-resistant contrast media line rated to 1200 psi for CT and angiography injectors.',
    price: 9400,
    mrp: 11500,
    gst: 12,
    hsn: '90183990',
    uom: 'Piece',
    packSize: '50 pcs / box',
    moq: 50,
    stock: 3260,
    lowStockAt: 800,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'Pressure Test Report', 'CE Certificate'],
    specs: [
      ['Length', '200 cm'],
      ['Pressure rating', '1200 psi'],
      ['Bore', '1.5 mm ID'],
      ['Connectors', 'Male / female luer lock'],
      ['Material', 'DEHP-free PVC'],
    ],
    applications: ['CT contrast injection', 'Angiography', 'Power injector circuits'],
    image: null,
  },
  {
    id: 'p-extension-low',
    code: 'AST-EX-3102',
    name: 'Low Pressure Extension Line 100 cm',
    category: 'Extension Lines',
    categorySlug: 'extension-lines',
    subCategory: 'Low Pressure',
    icon: 'vitals',
    summary: 'Standard luer lock extension line for routine infusion circuit extension.',
    price: 3200,
    mrp: 4100,
    gst: 12,
    hsn: '90183990',
    uom: 'Piece',
    packSize: '100 pcs / box',
    moq: 100,
    stock: 0,
    lowStockAt: 1000,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification'],
    specs: [
      ['Length', '100 cm'],
      ['Bore', '2.0 mm ID'],
      ['Connectors', 'Male / female luer lock'],
      ['Material', 'DEHP-free PVC'],
    ],
    applications: ['Routine infusion', 'General ward'],
    image: null,
  },
  {
    id: 'p-needlefree',
    code: 'AST-NF-4401',
    name: 'Needle-Free Connector, Split Septum',
    category: 'Connectors',
    categorySlug: 'connectors',
    subCategory: 'Needle-Free Connectors',
    icon: 'lab',
    summary: 'Neutral displacement split septum connector rated for 200 activations with a swabbable surface.',
    price: 7600,
    mrp: 9200,
    gst: 12,
    hsn: '90183990',
    uom: 'Piece',
    packSize: '100 pcs / box',
    moq: 100,
    stock: 8900,
    lowStockAt: 1500,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'CE Certificate', 'Microbial Ingress Report'],
    specs: [
      ['Activations', '200'],
      ['Displacement', 'Neutral'],
      ['Priming volume', '0.09 mL'],
      ['Septum', 'Split, swabbable'],
      ['Flow rate', '≥ 500 mL/hr'],
    ],
    applications: ['Central line access', 'Peripheral access', 'Blood sampling'],
    image: null,
  },
  {
    id: 'p-polyway-stopcock',
    code: 'AST-SC-5503',
    name: 'Polyway Three-Way Stop Cock with 10 cm Extension',
    category: 'Stop Cocks',
    categorySlug: 'stop-cocks',
    subCategory: null,
    icon: 'clinical',
    summary: 'Three-way stopcock with rotating male luer and colour-coded handle for line selection.',
    price: 5100,
    mrp: 6400,
    gst: 12,
    hsn: '90183990',
    uom: 'Piece',
    packSize: '100 pcs / box',
    moq: 100,
    stock: 820,
    lowStockAt: 1000,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'CE Certificate'],
    specs: [
      ['Ports', '3'],
      ['Extension', '10 cm'],
      ['Pressure rating', '300 psi'],
      ['Handle', 'Colour-coded, 360° rotation'],
      ['Material', 'Polycarbonate, lipid-resistant'],
    ],
    applications: ['Multi-line infusion', 'ICU', 'Operating theatre'],
    image: null,
  },
  {
    id: 'p-vial-spike',
    code: 'AST-VA-6601',
    name: 'Vial Access Spike with 0.2 µm Air Filter',
    category: 'Vial Access',
    categorySlug: 'vial-access',
    subCategory: null,
    icon: 'pharma',
    summary: 'Closed-system vial spike with hydrophobic air filter for repeated aseptic withdrawal.',
    price: 4900,
    mrp: 6100,
    gst: 12,
    hsn: '90183990',
    uom: 'Piece',
    packSize: '100 pcs / box',
    moq: 100,
    stock: 5410,
    lowStockAt: 1200,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'CE Certificate'],
    specs: [
      ['Air filter', '0.2 µm hydrophobic'],
      ['Spike', 'Universal, 13–32 mm vials'],
      ['Connector', 'Female luer lock'],
      ['Material', 'ABS / polycarbonate'],
    ],
    applications: ['Drug reconstitution', 'Pharmacy compounding', 'Chemotherapy prep'],
    image: null,
  },
  {
    id: 'p-saline-syringe',
    code: 'AST-PF-7702',
    name: 'Pre-filled Saline Flush Syringe 10 mL',
    category: 'Other Products',
    categorySlug: 'other-products',
    subCategory: null,
    icon: 'pharma',
    summary: 'Sterile 0.9% sodium chloride flush syringe, single use, for catheter patency maintenance.',
    price: 3850,
    mrp: 4800,
    gst: 12,
    hsn: '90183100',
    uom: 'Piece',
    packSize: '60 pcs / box',
    moq: 60,
    stock: 15600,
    lowStockAt: 3000,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'Batch Certificate', 'CE Certificate'],
    specs: [
      ['Volume', '10 mL'],
      ['Solution', '0.9% NaCl'],
      ['Barrel', 'Graduated, luer lock'],
      ['Shelf life', '24 months'],
    ],
    applications: ['Catheter flush', 'Line patency', 'Post-medication flush'],
    image: null,
  },
  {
    id: 'p-manifold',
    code: 'AST-MF-8801',
    name: 'Four-Gang Manifold with Rotating Adapters',
    category: 'Other Products',
    categorySlug: 'other-products',
    subCategory: null,
    icon: 'wound',
    summary: 'Four-port manifold with independent stopcocks for simultaneous multi-drug administration.',
    price: 21400,
    mrp: 26000,
    gst: 12,
    hsn: '90183990',
    uom: 'Piece',
    packSize: '25 pcs / box',
    moq: 25,
    stock: 260,
    lowStockAt: 300,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'CE Certificate'],
    specs: [
      ['Ports', '4'],
      ['Pressure rating', '300 psi'],
      ['Adapters', 'Rotating male luer'],
      ['Material', 'Lipid-resistant polycarbonate'],
    ],
    applications: ['Anaesthesia', 'Critical care', 'Multi-drug infusion'],
    image: null,
  },
  {
    id: 'p-flow-regulator',
    code: 'AST-FR-9903',
    name: 'I.V. Flow Regulator Extension Set 5–250 mL/hr',
    category: 'Extension Lines',
    categorySlug: 'extension-lines',
    subCategory: 'Low Pressure',
    icon: 'vitals',
    summary: 'Dial-controlled flow regulator with graduated 5–250 mL/hr scale, replacing gravity clamps.',
    price: 12600,
    mrp: 15400,
    gst: 12,
    hsn: '90183930',
    uom: 'Piece',
    packSize: '50 pcs / box',
    moq: 50,
    stock: 2140,
    lowStockAt: 600,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'Flow Accuracy Report', 'CE Certificate'],
    specs: [
      ['Flow range', '5–250 mL/hr'],
      ['Accuracy', '±10%'],
      ['Length', '20 cm'],
      ['Connectors', 'Male / female luer lock'],
    ],
    applications: ['Controlled gravity infusion', 'Ward without pumps', 'Ambulatory care'],
    image: null,
  },
  {
    id: 'p-transfer-spike',
    code: 'AST-TS-1105',
    name: 'Double-Ended Transfer Spike',
    category: 'Vial Access',
    categorySlug: 'vial-access',
    subCategory: null,
    icon: 'pharma',
    summary: 'Double-ended spike for closed transfer between vial and diluent container.',
    price: 4400,
    mrp: 5600,
    gst: 12,
    hsn: '90183990',
    uom: 'Piece',
    packSize: '100 pcs / box',
    moq: 100,
    stock: 3780,
    lowStockAt: 1000,
    status: 'discontinued',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification'],
    specs: [
      ['Spike', 'Double-ended, universal'],
      ['Material', 'ABS'],
    ],
    applications: ['Reconstitution', 'Closed transfer'],
    image: null,
  },

  // --------------------------------------------------------------------------
  // The rest of the catalogue. Shorter spec lists than the twelve above — these
  // exist so the listing page has something real to face: 34 products is enough
  // for pagination to matter, for facet counts to differ from each other, and for
  // a filter combination to legitimately return nothing. A 6-product fixture
  // makes every one of those cases untestable.
  // --------------------------------------------------------------------------

  {
    id: 'p-blood-transfusion',
    code: 'AST-BT-1210',
    name: 'Polyfusion Blood Transfusion Set with 200 µ Filter',
    category: 'I.V. Infusion',
    categorySlug: 'iv-infusion',
    subCategory: 'Filter Sets',
    icon: 'infusion',
    summary: 'Blood administration set with a 200 µ nylon mesh filter and a large-bore vented spike.',
    price: 8900,
    mrp: 11200,
    gst: 12,
    hsn: '90183930',
    uom: 'Piece',
    packSize: '50 pcs / box',
    moq: 50,
    stock: 2680,
    lowStockAt: 600,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'CE Certificate'],
    specs: [
      ['Filter', '200 µ nylon mesh'],
      ['Drop factor', '15 drops / mL'],
      ['Tube length', '150 cm'],
      ['Spike', 'Large bore, vented'],
    ],
    applications: ['Blood transfusion', 'Blood component therapy'],
    image: null,
  },
  {
    id: 'p-y-injection',
    code: 'AST-IV-1015',
    name: 'Polyfusion I.V. Set with Y-Injection Port',
    category: 'I.V. Infusion',
    categorySlug: 'iv-infusion',
    subCategory: 'Standard Infusion Sets',
    icon: 'infusion',
    summary: 'Standard gravity set with a latex-free Y-site for secondary medication delivery.',
    price: 5400,
    mrp: 6900,
    gst: 12,
    hsn: '90183930',
    uom: 'Piece',
    packSize: '100 pcs / box',
    moq: 100,
    stock: 9350,
    lowStockAt: 2000,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'CE Certificate'],
    specs: [
      ['Y-site', 'Latex-free, swabbable'],
      ['Drop factor', '20 drops / mL'],
      ['Tube length', '170 cm'],
    ],
    applications: ['Secondary infusion', 'Bolus medication', 'General ward'],
    image: null,
  },
  {
    id: 'p-filtered-set',
    code: 'AST-IV-1080',
    name: 'Polyfusion Filtered Infusion Set 0.2 µm In-Line',
    category: 'I.V. Infusion',
    categorySlug: 'iv-infusion',
    subCategory: 'Filter Sets',
    icon: 'infusion',
    summary: 'In-line 0.2 µm filter set for particulate and air elimination in critical infusions.',
    price: 24800,
    mrp: 29500,
    gst: 12,
    hsn: '90183930',
    uom: 'Piece',
    packSize: '25 pcs / box',
    moq: 25,
    stock: 640,
    lowStockAt: 300,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'CE Certificate', 'Filtration Efficiency Report'],
    specs: [
      ['Filter', '0.2 µm, positively charged'],
      ['Air eliminating', 'Yes, hydrophobic membrane'],
      ['Priming volume', '2.4 mL'],
    ],
    applications: ['Neonatal ICU', 'Parenteral nutrition', 'Critical care infusion'],
    image: null,
  },
  {
    id: 'p-amber-set',
    code: 'AST-IV-1092',
    name: 'Polyfusion Light-Protected Infusion Set, Amber',
    category: 'I.V. Infusion',
    categorySlug: 'iv-infusion',
    subCategory: 'Specialty Sets',
    icon: 'infusion',
    summary: 'Amber tubing set for photosensitive drugs, blocking transmission below 470 nm.',
    price: 16200,
    mrp: 19800,
    gst: 12,
    hsn: '90183930',
    uom: 'Piece',
    packSize: '25 pcs / box',
    moq: 25,
    stock: 380,
    lowStockAt: 400,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'Light Transmission Report'],
    specs: [
      ['Tubing', 'Amber, UV blocking'],
      ['Cut-off', '< 470 nm'],
      ['Drop factor', '20 drops / mL'],
    ],
    applications: ['Photosensitive drugs', 'Chemotherapy', 'Vitamin infusion'],
    image: null,
  },
  {
    id: 'p-enteral-set',
    code: 'AST-EF-1300',
    name: 'Polyfusion Enteral Feeding Set 1.2 m',
    category: 'I.V. Infusion',
    categorySlug: 'iv-infusion',
    subCategory: 'Specialty Sets',
    icon: 'infusion',
    summary: 'ENFit enteral feeding set with roller clamp, deliberately non-luer to prevent misconnection.',
    price: 11400,
    mrp: 14000,
    gst: 12,
    hsn: '90183930',
    uom: 'Piece',
    packSize: '50 pcs / box',
    moq: 50,
    stock: 1420,
    lowStockAt: 400,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'ISO 80369-3 Declaration'],
    specs: [
      ['Connector', 'ENFit, ISO 80369-3'],
      ['Length', '120 cm'],
      ['Clamp', 'Roller'],
    ],
    applications: ['Enteral nutrition', 'Gastrostomy feeding'],
    image: null,
  },
  {
    id: 'p-extension-high-150',
    code: 'AST-EX-3306',
    name: 'High Pressure Extension Line 150 cm, 1200 psi',
    category: 'Extension Lines',
    categorySlug: 'extension-lines',
    subCategory: 'High Pressure',
    icon: 'vitals',
    summary: 'Shorter contrast media line for bedside injector configurations, rated to 1200 psi.',
    price: 8600,
    mrp: 10500,
    gst: 12,
    hsn: '90183990',
    uom: 'Piece',
    packSize: '50 pcs / box',
    moq: 50,
    stock: 4120,
    lowStockAt: 800,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'Pressure Test Report'],
    specs: [
      ['Length', '150 cm'],
      ['Pressure rating', '1200 psi'],
      ['Bore', '1.5 mm ID'],
    ],
    applications: ['CT contrast injection', 'Power injector circuits'],
    image: null,
  },
  {
    id: 'p-coiled-extension',
    code: 'AST-EX-3210',
    name: 'Coiled Extension Line 90 cm',
    category: 'Extension Lines',
    categorySlug: 'extension-lines',
    subCategory: 'Low Pressure',
    icon: 'vitals',
    summary: 'Retractable coiled line that extends to 90 cm, reducing line tangle at the bedside.',
    price: 6200,
    mrp: 7800,
    gst: 12,
    hsn: '90183990',
    uom: 'Piece',
    packSize: '50 pcs / box',
    moq: 50,
    stock: 0,
    lowStockAt: 500,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification'],
    specs: [
      ['Extended length', '90 cm'],
      ['Retracted length', '22 cm'],
      ['Connectors', 'Male / female luer lock'],
    ],
    applications: ['Ambulatory infusion', 'Paediatric ward'],
    image: null,
  },
  {
    id: 'p-microbore',
    code: 'AST-EX-3050',
    name: 'Low Pressure Extension Line 30 cm, Microbore',
    category: 'Extension Lines',
    categorySlug: 'extension-lines',
    subCategory: 'Low Pressure',
    icon: 'vitals',
    summary: 'Microbore line with a 0.4 mL priming volume for accurate low-volume drug delivery.',
    price: 2900,
    mrp: 3700,
    gst: 12,
    hsn: '90183990',
    uom: 'Piece',
    packSize: '100 pcs / box',
    moq: 100,
    stock: 11200,
    lowStockAt: 2000,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification'],
    specs: [
      ['Length', '30 cm'],
      ['Priming volume', '0.4 mL'],
      ['Bore', '0.9 mm ID'],
    ],
    applications: ['Syringe pump infusion', 'Neonatal care'],
    image: null,
  },
  {
    id: 'p-y-extension',
    code: 'AST-EX-3410',
    name: 'Y-Type Extension Line with Two Needle-Free Ports',
    category: 'Extension Lines',
    categorySlug: 'extension-lines',
    subCategory: 'Low Pressure',
    icon: 'vitals',
    summary: 'Dual-port Y line allowing two simultaneous infusions through a single access site.',
    price: 13800,
    mrp: 16500,
    gst: 12,
    hsn: '90183990',
    uom: 'Piece',
    packSize: '50 pcs / box',
    moq: 50,
    stock: 1760,
    lowStockAt: 400,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'CE Certificate'],
    specs: [
      ['Ports', '2 needle-free'],
      ['Length', '25 cm'],
      ['Priming volume', '1.1 mL'],
    ],
    applications: ['Multi-drug infusion', 'ICU'],
    image: null,
  },
  {
    id: 'p-needlefree-positive',
    code: 'AST-NF-4410',
    name: 'Needle-Free Connector, Positive Displacement',
    category: 'Connectors',
    categorySlug: 'connectors',
    subCategory: 'Needle-Free Connectors',
    icon: 'lab',
    summary: 'Positive displacement connector that pushes fluid forward on disconnection to resist reflux.',
    price: 9200,
    mrp: 11400,
    gst: 12,
    hsn: '90183990',
    uom: 'Piece',
    packSize: '100 pcs / box',
    moq: 100,
    stock: 6300,
    lowStockAt: 1500,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'CE Certificate', 'Microbial Ingress Report'],
    specs: [
      ['Displacement', 'Positive'],
      ['Activations', '200'],
      ['Priming volume', '0.11 mL'],
    ],
    applications: ['Central line access', 'PICC lines'],
    image: null,
  },
  {
    id: 'p-combi-stopper',
    code: 'AST-CN-4520',
    name: 'Luer Lock Combi Stopper, Male and Female Pair',
    category: 'Connectors',
    categorySlug: 'connectors',
    subCategory: 'Other Connectors',
    icon: 'lab',
    summary: 'Sterile sealing cap pair for closing luer ports between uses.',
    price: 1400,
    mrp: 1900,
    gst: 12,
    hsn: '90183990',
    uom: 'Piece',
    packSize: '200 pcs / box',
    moq: 200,
    stock: 24800,
    lowStockAt: 4000,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification'],
    specs: [
      ['Type', 'Male and female pair'],
      ['Material', 'Polypropylene'],
    ],
    applications: ['Port sealing', 'Line closure'],
    image: null,
  },
  {
    id: 'p-rotating-adapter',
    code: 'AST-CN-4530',
    name: 'Rotating Male Luer Lock Adapter',
    category: 'Connectors',
    categorySlug: 'connectors',
    subCategory: 'Other Connectors',
    icon: 'lab',
    summary: '360° rotating adapter that prevents line torsion during repositioning.',
    price: 3100,
    mrp: 4000,
    gst: 12,
    hsn: '90183990',
    uom: 'Piece',
    packSize: '100 pcs / box',
    moq: 100,
    stock: 7900,
    lowStockAt: 1500,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification'],
    specs: [
      ['Rotation', '360°'],
      ['Pressure rating', '300 psi'],
    ],
    applications: ['Line repositioning', 'Operating theatre'],
    image: null,
  },
  {
    id: 'p-heparin-cap',
    code: 'AST-CN-4540',
    name: 'Heparin Cap, Latex-Free',
    category: 'Connectors',
    categorySlug: 'connectors',
    subCategory: 'Other Connectors',
    icon: 'lab',
    summary: 'Injection cap with a self-sealing latex-free septum for intermittent access.',
    price: 1800,
    mrp: 2400,
    gst: 12,
    hsn: '90183990',
    uom: 'Piece',
    packSize: '200 pcs / box',
    moq: 200,
    stock: 18400,
    lowStockAt: 4000,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification'],
    specs: [
      ['Septum', 'Self-sealing, latex-free'],
      ['Punctures', '20'],
    ],
    applications: ['Intermittent access', 'Heparin lock'],
    image: null,
  },
  {
    id: 'p-two-way-stopcock',
    code: 'AST-SC-5501',
    name: 'Two-Way Stop Cock, 300 psi',
    category: 'Stop Cocks',
    categorySlug: 'stop-cocks',
    subCategory: null,
    icon: 'clinical',
    summary: 'Compact two-port stopcock for simple on-off line control.',
    price: 3400,
    mrp: 4400,
    gst: 12,
    hsn: '90183990',
    uom: 'Piece',
    packSize: '100 pcs / box',
    moq: 100,
    stock: 5600,
    lowStockAt: 1000,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification'],
    specs: [
      ['Ports', '2'],
      ['Pressure rating', '300 psi'],
      ['Material', 'Polycarbonate'],
    ],
    applications: ['Line isolation', 'General ward'],
    image: null,
  },
  {
    id: 'p-four-way-stopcock',
    code: 'AST-SC-5510',
    name: 'Four-Way Stop Cock with 25 cm Extension',
    category: 'Stop Cocks',
    categorySlug: 'stop-cocks',
    subCategory: null,
    icon: 'clinical',
    summary: 'Four-port stopcock with colour-coded handle and integrated extension line.',
    price: 7300,
    mrp: 9100,
    gst: 12,
    hsn: '90183990',
    uom: 'Piece',
    packSize: '100 pcs / box',
    moq: 100,
    stock: 2240,
    lowStockAt: 800,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'CE Certificate'],
    specs: [
      ['Ports', '4'],
      ['Extension', '25 cm'],
      ['Pressure rating', '300 psi'],
    ],
    applications: ['Multi-line infusion', 'Anaesthesia'],
    image: null,
  },
  {
    id: 'p-hp-stopcock',
    code: 'AST-SC-5520',
    name: 'High Pressure Three-Way Stop Cock, 1200 psi',
    category: 'Stop Cocks',
    categorySlug: 'stop-cocks',
    subCategory: null,
    icon: 'clinical',
    summary: 'Angiography-rated three-way stopcock for contrast injector manifolds.',
    price: 10800,
    mrp: 13200,
    gst: 12,
    hsn: '90183990',
    uom: 'Piece',
    packSize: '50 pcs / box',
    moq: 50,
    stock: 890,
    lowStockAt: 400,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'Pressure Test Report', 'CE Certificate'],
    specs: [
      ['Ports', '3'],
      ['Pressure rating', '1200 psi'],
      ['Handle', 'Colour-coded'],
    ],
    applications: ['Angiography', 'Contrast injection'],
    image: null,
  },
  {
    id: 'p-chemo-spike',
    code: 'AST-VA-6610',
    name: 'Chemo Vial Access Spike, Closed System',
    category: 'Vial Access',
    categorySlug: 'vial-access',
    subCategory: null,
    icon: 'pharma',
    summary: 'Closed-system transfer spike with an activated carbon vapour filter for cytotoxic drugs.',
    price: 18600,
    mrp: 22400,
    gst: 12,
    hsn: '90183990',
    uom: 'Piece',
    packSize: '50 pcs / box',
    moq: 50,
    stock: 1080,
    lowStockAt: 400,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'CE Certificate', 'Containment Test Report'],
    specs: [
      ['Filter', '0.2 µm + activated carbon'],
      ['System', 'Closed, vapour containing'],
      ['Connector', 'Female luer lock'],
    ],
    applications: ['Chemotherapy preparation', 'Cytotoxic compounding'],
    image: null,
  },
  {
    id: 'p-mini-spike',
    code: 'AST-VA-6620',
    name: 'Mini Spike with Swabbable Valve',
    category: 'Vial Access',
    categorySlug: 'vial-access',
    subCategory: null,
    icon: 'pharma',
    summary: 'Compact vial spike with a swabbable valve for repeated needle-free withdrawal.',
    price: 6700,
    mrp: 8300,
    gst: 12,
    hsn: '90183990',
    uom: 'Piece',
    packSize: '100 pcs / box',
    moq: 100,
    stock: 4460,
    lowStockAt: 1000,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'CE Certificate'],
    specs: [
      ['Valve', 'Swabbable, needle-free'],
      ['Air filter', '0.2 µm hydrophobic'],
    ],
    applications: ['Multi-dose vials', 'Pharmacy compounding'],
    image: null,
  },
  {
    id: 'p-saline-5ml',
    code: 'AST-PF-7701',
    name: 'Pre-filled Saline Flush Syringe 5 mL',
    category: 'Other Products',
    categorySlug: 'other-products',
    subCategory: null,
    icon: 'pharma',
    summary: 'Sterile 0.9% sodium chloride flush syringe in a 5 mL fill for paediatric lines.',
    price: 3200,
    mrp: 4100,
    gst: 12,
    hsn: '90183100',
    uom: 'Piece',
    packSize: '60 pcs / box',
    moq: 60,
    stock: 8900,
    lowStockAt: 2000,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'Batch Certificate'],
    specs: [
      ['Volume', '5 mL'],
      ['Solution', '0.9% NaCl'],
      ['Shelf life', '24 months'],
    ],
    applications: ['Paediatric line flush', 'Catheter patency'],
    image: null,
  },
  {
    id: 'p-heparin-flush',
    code: 'AST-PF-7710',
    name: 'Pre-filled Heparin Flush Syringe 5 mL, 10 IU/mL',
    category: 'Other Products',
    categorySlug: 'other-products',
    subCategory: null,
    icon: 'pharma',
    summary: 'Heparinised saline flush syringe for locking central venous catheters.',
    price: 7400,
    mrp: 9200,
    gst: 12,
    hsn: '90183100',
    uom: 'Piece',
    packSize: '60 pcs / box',
    moq: 60,
    stock: 3120,
    lowStockAt: 800,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'Batch Certificate', 'CE Certificate'],
    specs: [
      ['Volume', '5 mL'],
      ['Concentration', '10 IU / mL'],
      ['Shelf life', '18 months'],
    ],
    applications: ['Central line lock', 'Port maintenance'],
    image: null,
  },
  {
    id: 'p-two-gang-manifold',
    code: 'AST-MF-8790',
    name: 'Two-Gang Manifold with Rotating Adapters',
    category: 'Other Products',
    categorySlug: 'other-products',
    subCategory: null,
    icon: 'wound',
    summary: 'Two-port manifold for simpler anaesthesia circuits where four ports are unnecessary.',
    price: 14200,
    mrp: 17400,
    gst: 12,
    hsn: '90183990',
    uom: 'Piece',
    packSize: '25 pcs / box',
    moq: 25,
    stock: 720,
    lowStockAt: 300,
    status: 'active',
    sterile: true,
    latexFree: true,
    documents: ['Technical Specification', 'CE Certificate'],
    specs: [
      ['Ports', '2'],
      ['Pressure rating', '300 psi'],
      ['Adapters', 'Rotating male luer'],
    ],
    applications: ['Anaesthesia', 'Critical care'],
    image: null,
  },
  {
    id: 'p-crepe-bandage',
    code: 'AST-WD-9010',
    name: 'Elastic Crepe Bandage 10 cm × 4 m',
    category: 'Other Products',
    categorySlug: 'other-products',
    subCategory: null,
    icon: 'wound',
    summary: 'Cotton crepe compression bandage with sustained recovery after repeated stretching.',
    price: 4600,
    mrp: 5900,
    gst: 12,
    hsn: '30059040',
    uom: 'Piece',
    packSize: '20 pcs / pack',
    moq: 20,
    stock: 6250,
    lowStockAt: 1000,
    status: 'active',
    // Not a sterile device, and saying so matters: the properties facet would
    // otherwise imply every product in the catalogue is sterile, which is the kind
    // of quiet inaccuracy a clinical buyer would catch and stop trusting.
    sterile: false,
    latexFree: true,
    documents: ['Technical Specification'],
    specs: [
      ['Size', '10 cm × 4 m'],
      ['Material', 'Cotton crepe'],
      ['Stretch', '~180%'],
    ],
    applications: ['Compression dressing', 'Sprain support'],
    image: null,
  },
];

/* -------------------------------------------------------------------------- */
/* Category counts — derived, never authored                                  */
/* -------------------------------------------------------------------------- */

// The counts in `categories` above used to be typed by hand, and they disagreed
// with the catalogue: the header dropdown offered "I.V. Infusion 34" and the
// filter it applied returned six. A count beside a filter is a promise about what
// clicking it does, so the only safe source for it is the list itself.
//
// Only `active` products count, because only active products are ever listed —
// see deriveCatalogue() in shop/catalogue.js, which drops the rest before it
// filters anything.
//
// This runs once at module load and mutates the objects in place so that every
// existing reader — the header dropdown, the mobile menu, the reference pages —
// picks it up without changing a line.
{
  const live = products.filter((p) => p.status === 'active');
  for (const category of categories) {
    const mine = live.filter((p) => p.categorySlug === category.slug);
    category.count = mine.length;
    for (const child of category.children ?? []) {
      child.count = mine.filter((p) => p.subCategory === child.name).length;
    }
  }
}

/* -------------------------------------------------------------------------- */
/* Organizations — §13. The buyer is an org, not a person.                    */
/* -------------------------------------------------------------------------- */

export const organizations = [
  {
    id: 'o-apollo-kondapur',
    legalName: 'Apollo Health Services Pvt Ltd',
    tradeName: 'Apollo Hospitals, Kondapur',
    type: 'Hospital',
    gstin: '36AABCA1234F1Z5',
    city: 'Hyderabad',
    state: 'Telangana',
    creditTerms: 'Net 45',
    creditLimit: 250000000,
    outstanding: 84200000,
    status: 'active',
    agentId: 'a-rakesh',
    orders: 42,
    since: '2024-03-11',
  },
  {
    id: 'o-sunrise-clinic',
    legalName: 'Sunrise Medicare LLP',
    tradeName: 'Sunrise Multi-Speciality Clinic',
    type: 'Clinic',
    gstin: '27AACFS9876K1ZP',
    city: 'Pune',
    state: 'Maharashtra',
    creditTerms: 'Net 30',
    creditLimit: 40000000,
    outstanding: 12650000,
    status: 'active',
    agentId: 'a-meera',
    orders: 18,
    since: '2025-01-22',
  },
  {
    id: 'o-medipoint',
    legalName: 'Medipoint Distributors',
    tradeName: 'Medipoint',
    type: 'Distributor',
    gstin: '29AAGFM5566L1Z2',
    city: 'Bengaluru',
    state: 'Karnataka',
    creditTerms: 'Net 60',
    creditLimit: 500000000,
    outstanding: 316000000,
    status: 'active',
    agentId: 'a-rakesh',
    orders: 96,
    since: '2023-07-04',
  },
  {
    id: 'o-lifeline-pharmacy',
    legalName: 'Lifeline Pharmacy',
    tradeName: 'Lifeline Pharmacy',
    type: 'Pharmacy',
    gstin: '33AAHFL2211M1ZQ',
    city: 'Chennai',
    state: 'Tamil Nadu',
    creditTerms: 'Advance',
    creditLimit: 0,
    outstanding: 0,
    status: 'pending',
    agentId: 'a-devika',
    orders: 0,
    since: '2026-08-02',
  },
  {
    id: 'o-citycare',
    legalName: 'CityCare Nursing Home Pvt Ltd',
    tradeName: 'CityCare Nursing Home',
    type: 'Hospital',
    gstin: '07AADCC7788N1ZR',
    city: 'New Delhi',
    state: 'Delhi',
    creditTerms: 'Net 30',
    creditLimit: 75000000,
    outstanding: 71900000,
    status: 'on-hold',
    agentId: 'a-devika',
    orders: 27,
    since: '2024-11-19',
  },
];

/* -------------------------------------------------------------------------- */
/* Agents — §14                                                               */
/* -------------------------------------------------------------------------- */

export const agents = [
  { id: 'a-rakesh', name: 'Rakesh Iyer', territory: 'South — Telangana, Karnataka', customers: 34, target: 450000000, achieved: 391000000, orders: 62, commission: 782000, conversion: 41 },
  { id: 'a-meera', name: 'Meera Nair', territory: 'West — Maharashtra, Gujarat', customers: 28, target: 380000000, achieved: 404000000, orders: 55, commission: 808000, conversion: 47 },
  { id: 'a-devika', name: 'Devika Rao', territory: 'North — Delhi NCR, Punjab', customers: 22, target: 300000000, achieved: 186000000, orders: 31, commission: 372000, conversion: 26 },
  { id: 'a-sanjay', name: 'Sanjay Menon', territory: 'East — West Bengal, Odisha', customers: 19, target: 250000000, achieved: 243000000, orders: 38, commission: 486000, conversion: 38 },
];

/* -------------------------------------------------------------------------- */
/* Orders — the §16 / §28 lifecycle, one row per state so a status column is   */
/* exercised across its whole range instead of showing "delivered" eight times */
/* -------------------------------------------------------------------------- */

export const orders = [
  { id: 'AST-26-0412', org: 'Apollo Hospitals, Kondapur', orgId: 'o-apollo-kondapur', agentId: 'a-rakesh', placed: '2026-08-11T09:12:00', status: 'placed', payment: 'pending', lines: 6, subtotal: 18420000, gst: 2210400, delivery: 400000, total: 21030400, po: 'PO/APL/26/8871' },
  { id: 'AST-26-0411', org: 'Medipoint', orgId: 'o-medipoint', agentId: 'a-rakesh', placed: '2026-08-10T16:40:00', status: 'confirmed', payment: 'partial', lines: 14, subtotal: 96400000, gst: 11568000, delivery: 0, total: 107968000, po: 'MP-2026-2210' },
  { id: 'AST-26-0409', org: 'Sunrise Multi-Speciality Clinic', orgId: 'o-sunrise-clinic', agentId: 'a-meera', placed: '2026-08-10T11:05:00', status: 'processing', payment: 'paid', lines: 3, subtotal: 7640000, gst: 916800, delivery: 400000, total: 8956800, po: 'SRC/PO/1142' },
  { id: 'AST-26-0407', org: 'CityCare Nursing Home', orgId: 'o-citycare', agentId: 'a-devika', placed: '2026-08-09T14:22:00', status: 'packed', payment: 'pending', lines: 9, subtotal: 31200000, gst: 3744000, delivery: 400000, total: 35344000, po: 'CC/26/0771' },
  { id: 'AST-26-0405', org: 'Apollo Hospitals, Kondapur', orgId: 'o-apollo-kondapur', agentId: 'a-rakesh', placed: '2026-08-08T10:31:00', status: 'dispatched', payment: 'paid', lines: 11, subtotal: 54800000, gst: 6576000, delivery: 0, total: 61376000, po: 'PO/APL/26/8802' },
  { id: 'AST-26-0402', org: 'Medipoint', orgId: 'o-medipoint', agentId: 'a-rakesh', placed: '2026-08-06T09:00:00', status: 'inTransit', payment: 'paid', lines: 22, subtotal: 142600000, gst: 17112000, delivery: 0, total: 159712000, po: 'MP-2026-2198' },
  { id: 'AST-26-0398', org: 'Sunrise Multi-Speciality Clinic', orgId: 'o-sunrise-clinic', agentId: 'a-meera', placed: '2026-08-04T15:47:00', status: 'outForDelivery', payment: 'paid', lines: 4, subtotal: 9120000, gst: 1094400, delivery: 400000, total: 10614400, po: 'SRC/PO/1138' },
  { id: 'AST-26-0391', org: 'CityCare Nursing Home', orgId: 'o-citycare', agentId: 'a-devika', placed: '2026-08-01T12:15:00', status: 'delivered', payment: 'paid', lines: 7, subtotal: 26400000, gst: 3168000, delivery: 400000, total: 29968000, po: 'CC/26/0754' },
  { id: 'AST-26-0388', org: 'Lifeline Pharmacy', orgId: 'o-lifeline-pharmacy', agentId: 'a-devika', placed: '2026-07-30T17:03:00', status: 'cancelled', payment: 'refunded', lines: 2, subtotal: 3800000, gst: 456000, delivery: 400000, total: 4656000, po: '—' },
  { id: 'AST-26-0384', org: 'Medipoint', orgId: 'o-medipoint', agentId: 'a-rakesh', placed: '2026-07-28T08:52:00', status: 'returned', payment: 'refunded', lines: 5, subtotal: 15200000, gst: 1824000, delivery: 0, total: 17024000, po: 'MP-2026-2181' },
];

/** The §28 audit trail for one order. Every transition, who did it, when. */
export const orderHistory = [
  { status: 'placed', at: '2026-08-08T10:31:00', by: 'Rakesh Iyer (Agent)', note: 'Placed against PO/APL/26/8802' },
  { status: 'confirmed', at: '2026-08-08T11:02:00', by: 'Priya Sharma (Admin)', note: 'Credit limit checked — ₹1.66L headroom' },
  { status: 'processing', at: '2026-08-08T14:20:00', by: 'Warehouse — Hyderabad', note: 'Stock reserved across 11 lines' },
  { status: 'packed', at: '2026-08-09T09:15:00', by: 'Warehouse — Hyderabad', note: '3 cartons, 42.4 kg' },
  { status: 'dispatched', at: '2026-08-09T16:48:00', by: 'Priya Sharma (Admin)', note: 'Bluedart · AWB 77291184450' },
];

/** Order line items, for the detail screens and the GST breakdown pattern. */
export const orderLines = [
  { code: 'AST-IV-1001', name: 'Polyfusion I.V. Infusion Set with Airvent Spike', qty: 500, uom: 'Piece', rate: 4250, gst: 12 },
  { code: 'AST-NF-4401', name: 'Needle-Free Connector, Split Septum', qty: 300, uom: 'Piece', rate: 7600, gst: 12 },
  { code: 'AST-SC-5503', name: 'Polyway Three-Way Stop Cock with 10 cm Extension', qty: 200, uom: 'Piece', rate: 5100, gst: 12 },
  { code: 'AST-PF-7702', name: 'Pre-filled Saline Flush Syringe 10 mL', qty: 600, uom: 'Piece', rate: 3850, gst: 12 },
];

/* -------------------------------------------------------------------------- */
/* Quotes — §15. First-class in B2B, which is why they get their own states.   */
/* -------------------------------------------------------------------------- */

export const quotes = [
  { id: 'QT-26-0091', org: 'Apollo Hospitals, Kondapur', agentId: 'a-rakesh', raised: '2026-08-11T08:40:00', validTill: '2026-08-25', lines: 8, value: 42600000, status: 'sent' },
  { id: 'QT-26-0089', org: 'Lifeline Pharmacy', agentId: 'a-devika', raised: '2026-08-10T13:20:00', validTill: '2026-08-24', lines: 3, value: 6400000, status: 'underReview' },
  { id: 'QT-26-0086', org: 'Medipoint', agentId: 'a-rakesh', raised: '2026-08-07T10:10:00', validTill: '2026-08-21', lines: 19, value: 128400000, status: 'approved' },
  { id: 'QT-26-0081', org: 'CityCare Nursing Home', agentId: 'a-devika', raised: '2026-08-02T16:55:00', validTill: '2026-08-16', lines: 5, value: 18900000, status: 'expired' },
  { id: 'QT-26-0078', org: 'Sunrise Multi-Speciality Clinic', agentId: 'a-meera', raised: '2026-07-29T09:30:00', validTill: '2026-08-12', lines: 6, value: 22100000, status: 'converted' },
];

/* -------------------------------------------------------------------------- */
/* Dashboard figures — §19, §20                                               */
/* -------------------------------------------------------------------------- */

export const metrics = [
  { label: 'Revenue', value: 124850000, delta: 12.4, kind: 'money', context: 'vs previous month' },
  { label: 'Orders', value: 348, delta: 6.1, kind: 'count', context: 'vs previous month' },
  { label: 'Customers', value: 126, delta: 2.4, kind: 'count', context: '4 new this month' },
  { label: 'Outstanding', value: 48470000, delta: -8.2, kind: 'money', context: 'across 23 invoices' },
];

/** Twelve months of revenue and orders. Revenue in paise. */
export const revenueSeries = [
  { month: 'Sep', revenue: 78400000, orders: 214 },
  { month: 'Oct', revenue: 91200000, orders: 246 },
  { month: 'Nov', revenue: 86500000, orders: 231 },
  { month: 'Dec', revenue: 104300000, orders: 288 },
  { month: 'Jan', revenue: 97800000, orders: 268 },
  { month: 'Feb', revenue: 88900000, orders: 242 },
  { month: 'Mar', revenue: 118600000, orders: 322 },
  { month: 'Apr', revenue: 102400000, orders: 279 },
  { month: 'May', revenue: 109700000, orders: 301 },
  { month: 'Jun', revenue: 96300000, orders: 264 },
  { month: 'Jul', revenue: 111100000, orders: 308 },
  { month: 'Aug', revenue: 124850000, orders: 348 },
];

export const topProducts = [
  { name: 'Polyfusion I.V. Infusion Set', revenue: 31400000, units: 7388 },
  { name: 'Needle-Free Connector', revenue: 24800000, units: 3263 },
  { name: 'High Pressure Extension Line', revenue: 19600000, units: 2085 },
  { name: 'Pre-filled Saline Flush Syringe', revenue: 16200000, units: 4207 },
  { name: 'Polyway Three-Way Stop Cock', revenue: 12900000, units: 2529 },
];

/** §22 notification events, for the bell menu and the agent follow-up list. */
export const notifications = [
  { id: 'n1', tone: 'warning', title: 'Low stock — Polyfusion Micro Drip Set', body: '1,840 units left, below the 2,000 threshold.', at: '2026-08-11T09:40:00', unread: true },
  { id: 'n2', tone: 'info', title: 'Quote QT-26-0091 sent to Apollo', body: 'Valid until 25 Aug 2026.', at: '2026-08-11T08:41:00', unread: true },
  { id: 'n3', tone: 'success', title: 'Payment received — AST-26-0409', body: '₹89,568.00 against SRC/PO/1142.', at: '2026-08-10T11:22:00', unread: false },
  { id: 'n4', tone: 'error', title: 'CityCare Nursing Home on credit hold', body: 'Outstanding ₹7,19,000 against a ₹7,50,000 limit.', at: '2026-08-09T15:10:00', unread: false },
];
